#!/bin/bash
#
# Shell script to start the Pritunl Docker image.
#
# Copyright 2019, Tarbase. All Rights Reserved
#   Author: Frederico Martins <http://github.com/fscm>
#

set -e

if ! [ -z "$1" ]; then
  exec "$@"
  exit 0
fi

MONGODB_DATA="/data/mongodb"

if [ -z "$MONGODB_URI" ]; then
  echo "[INFO] Starting local MongoDB..."
  # Create data dir (if needed)
  if ! [ -d ${MONGODB_DATA} ]; then
    mkdir -m 0755 ${MONGODB_DATA}
  fi
  # start the db
  mongod --bind_ip '127.0.0.1' --dbpath "${MONGODB_DATA}" &
else
  echo "[INFO] Setting MongoDB URI..."
  # set the mongo_uri
  pritunl set-mongodb "${MONGODB_URI}"
fi

echo "[INFO] Starting Pritunl..."
# start pritunl
pritunl start

exit 0
